---
abstract: 'Perl interface to Django-inspired Swig templating engine.'
author:
  - 'David Chester <dchester@shutterstock.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Swig
no_index:
  directory:
    - t
    - inc
requires:
  JSON::XS: 0
  JavaScript::V8: 0
  Test::Exception: 0
  Test::More: 0
version: 0.01
