--- #YAML:1.0
name:               Template-Swig
version:            0.03
abstract:           Perl interface to Django-inspired Swig templating engine.
author:
    - David Chester <dchester@shutterstock.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:      0
    JavaScript::V8:   0
    JSON::XS:         0
    Test::Exception:  0
    Test::More:       0
resources:
    repository:  https://github.com/dchester/perl-template-swig
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
